// Generated by ./scripts/setup_firebase.sh (`flutterfire configure`).
// These placeholders compile but must be replaced before a real Firebase build.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform. '
          'Run `./scripts/setup_firebase.sh` for the prod Firebase project.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REPLACE_ME_PROD_ANDROID_API_KEY',
    appId: '1:000000000000:android:0000000000000000',
    messagingSenderId: '000000000000',
    projectId: '__PROD_FIREBASE_PROJECT_ID__',
    storageBucket: '__PROD_FIREBASE_PROJECT_ID__.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_ME_PROD_IOS_API_KEY',
    appId: '1:000000000000:ios:0000000000000000',
    messagingSenderId: '000000000000',
    projectId: '__PROD_FIREBASE_PROJECT_ID__',
    storageBucket: '__PROD_FIREBASE_PROJECT_ID__.appspot.com',
    iosBundleId: '__IOS_BUNDLE_ID__',
  );
}
