/// Compile-time app identity generated from [project_config.yaml].
///
/// Generated by ./scripts/setup_project.sh on 2026-09-10.
class AppIdentity {
  AppIdentity._();

  static const String appName = "Template Implementation";
  static const String dartPackage = "app_template";
  static const String androidPackage = "com.template.implementation";
  static const String iosBundleId = "__IOS_BUNDLE_ID__";
  static const String supportEmail = "\"test@gmail.com\u001b[C\u001b[D\"";
  static const String termsUrl = "fsfg";
  static const String privacyUrl = "fgr";
  static const String refundUrl = "rtrg";
  static const String deeplinkScheme = "template";
  static const String deeplinkHost = "__DEEPLINK_HOST__";
}
